export const authCopy = {
  zh: {
    login: '登录', account: '我的账户', title: '欢迎来到云谷404', subtitle: '用邮箱登录，让好想法在这里相遇。',
    steps: '登录步骤', emailStep: '填写邮箱', codeStep: '验证邮箱', passwordless: '邮箱验证 · 无需密码',
    emailHint: '我们会向此邮箱发送 6 位验证码。', emailRequired: '请先填写邮箱地址。',
    emailFormat: '邮箱格式不正确，例如 you@example.com。', codeRequired: '请输入邮件中的 6 位验证码。',
    codeFormat: '验证码应为 6 位数字。', codeHint: '可直接粘贴邮件中的验证码。', codeExpired: '验证码已过期，请重新发送。',
    codeValidity: '10 分钟内有效', verified: '邮箱已验证',
    email: '邮箱地址', emailPlaceholder: 'you@example.com', send: '发送验证码', sending: '正在发送…',
    notice: '首次验证邮箱将自动创建账户，无需设置密码。', codeTitle: '查收你的验证码',
    sent: '验证码已发送至', code: '6 位验证码', verify: '登录', verifying: '正在验证…',
    changeEmail: '修改邮箱', resend: '重新发送', resendIn: s => `${s} 秒后可重发`,
    help: '验证码 10 分钟内有效。未收到？请检查垃圾邮件，或确认邮箱地址是否正确。',
    userId: '用户 ID', nickname: '昵称', nicknamePlaceholder: '怎么称呼你？', nicknameHelp: '选填，最多 32 个字符。',
    save: '保存昵称', saving: '正在保存…', saved: '昵称已保存', logout: '退出登录', logoutAll: '退出所有设备',
    logoutAllHint: '所有设备都需要重新验证邮箱。', working: '正在处理…', close: '关闭',
    expiredSession: '登录已过期，请重新验证邮箱。', loading: '正在读取账户…',
    errors: {
      invalid_email: '请输入有效的邮箱地址。', invalid_code: '验证码不正确、已过期或已使用，请检查或重新获取。',
      rate_limited: '操作有些频繁，请稍后再试。', email_unavailable: '邮件暂时发送失败，请稍后重新发送。',
      unavailable: '登录服务暂时不可用，请稍后再试。', invalid_nickname: '昵称最多 32 个字符，请勿使用控制字符。',
      forbidden: '请求未通过安全校验，请刷新页面后重试。', network: '网络连接失败，请重试。',
    },
  },
  en: {
    login: 'Sign in', account: 'My account', title: 'Welcome to Cloud Valley 404', subtitle: 'Sign in with your email. Make room for your next idea.',
    steps: 'Sign-in steps', emailStep: 'Your email', codeStep: 'Verify email', passwordless: 'Email verification · No password',
    emailHint: 'We’ll send a 6-digit code to this address.', emailRequired: 'Enter your email address.',
    emailFormat: 'Use a valid email address, like you@example.com.', codeRequired: 'Enter the 6-digit code from your email.',
    codeFormat: 'Your code must contain exactly 6 digits.', codeHint: 'You can paste the code directly from your email.', codeExpired: 'This code has expired. Request a new one.',
    codeValidity: 'Valid for 10 minutes', verified: 'Email verified',
    email: 'Email address', emailPlaceholder: 'you@example.com', send: 'Send code', sending: 'Sending…',
    notice: 'New here? Verifying your email creates an account. No password needed.', codeTitle: 'Check your inbox',
    sent: 'We sent a code to', code: '6-digit code', verify: 'Sign in', verifying: 'Verifying…',
    changeEmail: 'Change email', resend: 'Resend code', resendIn: s => `Resend in ${s}s`,
    help: 'Your code expires in 10 minutes. No email? Check your spam folder or the email address above.',
    userId: 'User ID', nickname: 'Nickname', nicknamePlaceholder: 'What should we call you?', nicknameHelp: 'Optional, up to 32 characters.',
    save: 'Save nickname', saving: 'Saving…', saved: 'Nickname saved', logout: 'Sign out', logoutAll: 'Sign out everywhere',
    logoutAllHint: 'You will need to verify your email again on every device.', working: 'Working…', close: 'Close',
    expiredSession: 'Your session expired. Please sign in again.', loading: 'Loading account…',
    errors: {
      invalid_email: 'Enter a valid email address.', invalid_code: 'This code is incorrect, expired or already used. Check it or request a new one.',
      rate_limited: 'Too many attempts. Please try again later.', email_unavailable: 'We could not send your email. Please try again shortly.',
      unavailable: 'Sign-in is temporarily unavailable. Please try again later.', invalid_nickname: 'Use up to 32 characters, without control characters.',
      forbidden: 'The security check failed. Refresh the page and try again.', network: 'Connection failed. Please try again.',
    },
  },
};
