export const copy = {
  zh: {
    title: "云谷404 · 好想法，正在放映",
    guideTitle: "创作指南 · 云谷404",
    skip: "跳到电视内容",
    home: "云谷404 首页",
    location: "中国 · 杭州 · 云谷",
    join: "一起做点东西",
    intro: "好想法，正在放映",
    channels: ["主频道", "作品放映", "活动现场", "关于我们"],
    choose: "选择你的频道",
    channelNav: "电视频道",
    next: "切换到下一个频道",
    knob: "转个频道",
    tv: "云谷404 创作电视",
    controls: "电视控制",
    powerOn: "打开电视",
    powerOff: "关闭电视",
    standby: "好想法，稍后继续。",
    offStatus: "电视已关闭，点击电源或选择频道开机。",
    playing: "正在放映：",
    soundOn: "开启氛围声",
    soundOff: "关闭氛围声",
    soundError: "当前浏览器暂不支持氛围声。",
    tuneHint: "换个频道，发现点新东西。",
    curious: "保持好奇，保持开机。",
    footer: "从一个想法，到一次被看见。",
    guideLink: "创作指南",
    back: "返回活动频道",
    backHome: "回到电视",
    light: "切换到日间模式",
    dark: "切换到夜间模式",
    preferences: "显示和语言设置",
    hero: ["让好想法，", "不再"],
    heroBody: ["在杭州云谷，和一群动手的人，", "把想法做成可以体验的作品。"],
    heroCta: "看看创作频道",
    motto: "把作品做出来、讲清楚、发出去",
    worksLabel: "404 WORKS / 作品放映",
    worksTitle: ["下一个上屏的，", "可以是你的作品。"],
    worksBody:
      "一个小工具、一款小游戏，或一个终于跑通的想法。让别人打开它、试一试，再给你一点真实反馈。",
    steps: [
      ["能打开", "一个可体验的核心流程"],
      ["讲得清", "一句话说明解决什么问题"],
      ["发出去", "给作品一个被看见的入口"],
    ],
    worksCta: "我也有个作品",
    worksNote: "作品征集中 · 等你来放映",
    eventsLabel: "404 BUILD / 活动现场",
    archive: "第一期 · 活动档案",
    eventTitle: ["一个下午，", "让想法开始运行。"],
    eventBody:
      "云谷404 迷你黑客松：从现场开发到上台演示，完成一个小红书小工具。",
    venue: "云谷中心 B2-3F 活动区",
    eventCta: "打开参赛指南",
    poster: "查看海报",
    posterAlt: "云谷404 迷你黑客松第一期活动海报（中文）",
    aboutLabel: "ABOUT / 关于云谷404",
    aboutTitle: ["好想法，", "值得一个真实的现场。"],
    aboutBody:
      "云谷404，是杭州云谷的 AI Builder 作品发布场。我们把开发者、创作者和想动手的人聚在一起，从一个想法开始，做出作品，分享过程，也认识彼此。",
    roots: "扎根杭州云谷",
    makers: "为动手的人而来",
    aboutCta: "找到你的同频伙伴",
    dialogTitle: "带着你的想法来。",
    dialogBody: "你可以带来一个刚起步的点子，也可以带来一个已经能打开的作品。",
    close: "关闭参与说明",
    joinSteps: [
      ["做作品", "先做出一个能体验的核心流程。"],
      ["来分享", "准备一句话介绍和一次真实演示。"],
      ["认识同频的人", "一起试用、交流，把作品继续做下去。"],
    ],
    pending: "下一期活动及参与入口将在这里公布。",
    dialogCta: "先看看创作指南",
    guide: {
      label: "404 BUILD / VOL.001 / 创作指南",
      title: ["先做出一个", "能被体验的版本。"],
      intro:
        "这是云谷404第一期迷你黑客松的参赛指南。我们围绕小红书小工具，完成现场开发、演示、投票和上传。",
      note: "第一期活动资料存档。平台规范可能更新，当前限制与上传要求请以小红书官方文档和后台为准。",
      sections: [
        {
          title: "01 / 带什么作品来？",
          paragraphs: [
            "作品不需要庞大。围绕一个明确的问题，完成一个可以操作的核心页面，先跑通一条完整流程。",
          ],
          items: [
            "一个可以完整体验核心流程的作品；",
            "一个符合小红书小工具规范、可上传的 ZIP 包；",
            "一段能讲清问题、并完成真实操作的现场演示。",
          ],
        },
        {
          title: "02 / 现场怎么进行？",
          ordered: true,
          items: [
            "认识彼此。自愿介绍，每人最多30秒：你是谁、你在做什么、今天想做什么。",
            "开始 Coding。个人参赛，先实现核心操作，再完善移动端适配和视觉细节。",
            "上台演示。一句话说明作品解决什么问题，然后完整操作一次。",
            "互相投票。看得懂、跑得通、记得住，把票投给你希望继续看到的作品。",
            "发布与合影。保留作品和演示入口，把它作为认识新朋友的名片。",
          ],
        },
        {
          title: "03 / 开发时，记住这几件事。",
          paragraphs: [
            "第一期使用离线 H5 小工具交付方式：资源放进包里，使用相对路径，适配手机安全区。不要依赖远程接口、CDN 或在线字体。",
            "ZIP 根目录直接放 index.html；脚本放在外部 JS 文件中；使用事件监听完成交互。具体包大小、Bridge 能力及容器限制，请在发布前核对官方要求。",
          ],
          platform: true,
        },
        {
          title: "04 / 演示之前，走完一遍。",
          items: [
            "入口能打开，第一眼知道作品做什么；",
            "关键流程能从头到尾，结果页能重试或返回；",
            "连续点击、快速切换不会卡住；",
            "手机上没有横向溢出，文字和按钮没有被遮挡；",
            "已在平台预览和至少一台真机上体验核心流程；",
            "已经备份最终 ZIP，并排练过一次演示。",
          ],
          after:
            "自动校验和普通浏览器测试，不能代替真实容器验证。把最后一点时间留给测试和演示。",
        },
      ],
      platform: "打开小红书创作服务平台",
      quote: "先做出来，讲清楚，再发出去。",
      download: "下载第一期完整指南（中文）",
    },
    notFound: "这个频道暂时没有信号。",
  },
  en: {
    title: "Yungu404 · Good ideas on air",
    guideTitle: "Creator guide · Yungu404",
    skip: "Skip to television",
    home: "Yungu404 home",
    location: "YUNGU · HANGZHOU · CHINA",
    join: "Make something",
    intro: "Good ideas on air",
    channels: ["Home", "Works", "Events", "About"],
    choose: "Choose a channel",
    channelNav: "TV channels",
    next: "Next channel",
    knob: "Tune in",
    tv: "Yungu404 creator television",
    controls: "Television controls",
    powerOn: "Turn on TV",
    powerOff: "Turn off TV",
    standby: "Good ideas. Back in a moment.",
    offStatus: "TV is off. Press power or choose a channel to begin.",
    playing: "Now showing: ",
    soundOn: "Enable ambient sound",
    soundOff: "Mute ambient sound",
    soundError: "Ambient sound is unavailable in this browser.",
    tuneHint: "Change channels. Find something new.",
    curious: "Stay curious. Stay tuned.",
    footer: "From an idea to being seen.",
    guideLink: "Creator guide",
    back: "Back to events",
    backHome: "Back to TV",
    light: "Switch to light mode",
    dark: "Switch to dark mode",
    preferences: "Appearance and language",
    hero: ["Good ideas.", "No more"],
    heroBody: [
      "Meet people who make, in Yungu, Hangzhou.",
      "Turn your idea into something people can try.",
    ],
    heroCta: "Explore the works",
    motto: "Build it. Explain it. Put it out there.",
    worksLabel: "404 WORKS / ON SCREEN",
    worksTitle: ["Next on screen?", "It could be yours."],
    worksBody:
      "A small tool, a little game, or an idea that finally works. Let someone try it and give you real feedback.",
    steps: [
      ["Make it work", "One complete, usable flow"],
      ["Tell its story", "One problem, clearly explained"],
      ["Put it out", "Give your work a public home"],
    ],
    worksCta: "I have something to show",
    worksNote: "Calling for works · Yours could be next",
    eventsLabel: "404 BUILD / IN PERSON",
    archive: "Vol.001 · Event archive",
    eventTitle: ["One afternoon.", "An idea comes alive."],
    eventBody:
      "Yungu404 Mini Hackathon: build a Xiaohongshu mini-tool, then take it on stage for a live demo.",
    venue: "Yungu Center · B2, 3F event space",
    eventCta: "Read the creator guide",
    poster: "View poster",
    posterAlt: "Yungu404 Mini Hackathon Vol.001 poster (Chinese)",
    aboutLabel: "ABOUT / YUNGU404",
    aboutTitle: ["Good ideas deserve", "a place to happen."],
    aboutBody:
      "Yungu404 is a place for AI Builders to launch their work in Yungu, Hangzhou. Developers, creators, and curious people come together to build, share the process, and get to know one another.",
    roots: "Rooted in Yungu, Hangzhou",
    makers: "For people who make",
    aboutCta: "Find your kind of people",
    dialogTitle: "Bring your idea.",
    dialogBody:
      "Come with a first spark or a working project. There is room for both.",
    close: "Close participation details",
    joinSteps: [
      ["Make something", "Start with one flow people can actually try."],
      ["Share it", "Prepare a one-line introduction and a live demo."],
      [
        "Meet fellow makers",
        "Try things together, exchange feedback, and keep building.",
      ],
    ],
    pending: "The next event and participation details will be announced here.",
    dialogCta: "Start with the creator guide",
    guide: {
      label: "404 BUILD / VOL.001 / CREATOR GUIDE",
      title: ["Start with something", "people can try."],
      intro:
        "This is the guide for the first Yungu404 Mini Hackathon. Participants built Xiaohongshu mini-tools, demonstrated them, voted, and prepared their uploads.",
      note: "Archived event material. Platform rules may change; check current requirements in the official Xiaohongshu documentation and creator dashboard.",
      sections: [
        {
          title: "01 / What should you bring?",
          paragraphs: [
            "Keep it small. Pick one clear problem and build a core screen with a complete, usable flow.",
          ],
          items: [
            "A project with one complete core experience.",
            "A ZIP package that meets the platform requirements.",
            "A live demo that explains the problem and shows the project working.",
          ],
        },
        {
          title: "02 / How does the event work?",
          ordered: true,
          items: [
            "Meet each other. Optional introductions, up to 30 seconds: who you are, what you make, and what you want to build today.",
            "Start coding. Work individually on the core flow, then refine the mobile experience and visual details.",
            "Give a demo. Explain the problem in one sentence, then show the complete flow.",
            "Vote for each other. Choose a project you understand, can use, and want to see grow.",
            "Publish and take a photo. Keep your project and demo link as a way to introduce yourself.",
          ],
        },
        {
          title: "03 / A few things to remember.",
          paragraphs: [
            "The first event used offline HTML mini-tools. Bundle assets locally, use relative paths, and account for mobile safe areas. Avoid remote APIs, CDNs, and online fonts.",
            "Put index.html at the ZIP root. Keep JavaScript in external files and use event listeners. Verify the current package-size limits, bridge capabilities, and container restrictions before publishing.",
          ],
          platform: true,
        },
        {
          title: "04 / Walk through it before the demo.",
          items: [
            "The entry screen opens and explains what the project does.",
            "The core flow works end to end, with a retry or return option.",
            "Rapid taps and repeated actions do not freeze the interface.",
            "On mobile, there is no horizontal overflow or obscured content.",
            "You have tested the core flow in the platform preview and on a real device.",
            "The final ZIP is backed up and you have rehearsed the demo.",
          ],
          after:
            "Automated checks and a desktop browser do not replace testing in the real container. Save time for testing and rehearsal.",
        },
      ],
      platform: "Open Xiaohongshu Creator Center",
      quote: "Build it. Explain it. Put it out there.",
      download: "Download the original guide (Chinese)",
    },
    notFound: "There is no signal on this channel.",
  },
};
