export const hackathonCopy = {
  zh: {
    label: '云谷404 · 第二期黑客松', badge: '报名意向征集中', title: ['让 AI 做出', '下一步决定。'],
    intro: '选一个真实场景，让 Jev 做关键判断，再由程序采取行动。带上你的问题，做出能演示“输入 → 判断 → 动作”的作品。',
    apply: '申请参加', learn: '认识 Jev', poster: '查看最新海报', back: '返回活动', date: '活动时间', place: '活动地点', capacity: '人数 / 费用', dateValue: '09.27 · 10:00–20:00', placeValue: '云谷中心 B2-3F 活动区', capacityValue: '免费报名 · 限 30 名',
    pendingInfo: '活动于 9 月 27 日 10:00–20:00 在云谷中心 B2-3F 活动区举行，免费报名、限 30 名。比赛提供模型使用额度；具体领取及使用规则以主办方通知为准。提交报名意向不代表获得席位。',
    about: '给软件一个判断力。', aboutBody: 'Jev 是 TypeSafe AI 的 System One 模型。给它上下文和明确的问题，拿到程序可直接使用的结构化结果，再由你的代码决定下一步。',
    primitives: [['Choice', '选一条路', '从你定义的选项中选择，返回各选项概率与 confidence。'], ['Score', '衡量一个维度', '按明确的等级标准评分，返回分值、概率与 confidence。'], ['Noul', '判断一件事', '返回一个命题为真的概率（0–1），没有独立的 confidence 字段。']],
    limit: 'Jev 适合定义清楚的分类、打分与判断。confidence 不等于正确率；阈值要按场景风险测试，并为不确定的结果准备人工复核或其他回退。',
    lab: '一个判断，三条去路。', labHint: '点击切换工单，看看决策如何连接产品。', demo: '交互示意 · 预设数据，未调用 Jev', input: '用户输入', question: '应该交给谁？', output: '程序执行',
    examples: [
      { name: '重复扣费', text: '这笔订单扣了两次钱，能帮我查一下吗？', choice: 'billing', confidence: '0.94', action: '转交账单支持', values: [94, 4, 2] },
      { name: '功能故障', text: '每次点击导出，页面就会报错。', choice: 'technical', confidence: '0.92', action: '转交技术支持', values: [3, 92, 5] },
      { name: '信息不足', text: '我的账户好像有点问题……', choice: 'other', confidence: '0.18', action: '信息不足 → 人工确认', values: [29, 30, 41] },
    ],
    tracksTitle: '从一个小问题开始。', tracksIntro: '选择你感兴趣的方向，也欢迎带来自己的题目。',
    tracks: [['router', '01', '聪明的分流器', '让消息、工单或任务，去到正确的人或模型。', 'Choice → route'], ['agent', '02', 'Agent 的下一步', '给工具调用增加判断：继续、补充信息，还是交给人。', 'Noul → gate'], ['workflow', '03', '会判断的工作流', '筛选内容、整理反馈、排列优先级，减少重复判断。', 'Score → rank']],
    plan: '一天，做出来。', planIntro: '9 月 27 日 · 10:00–20:00 · 活动流程',
    steps: [['10:00–10:30', '签到开场：Jev 模型能力速览与开发资源介绍'], ['10:30–11:00', '自由组队与选题确认'], ['11:00–18:00', '集中开发，巡场答疑'], ['18:00–19:30', '项目 Demo 路演与评审'], ['19:30–20:00', '结果公布、颁奖与自由交流']],
    deliver: '演示完整的判断链路。', deliverBody: '建议交付：一个可操作 Demo、至少一次真实 Jev 调用、约 10 条自建测试样例，以及不确定或失败时的回退。可以使用已有项目和 AI 编程工具；演示时说明活动期间完成的部分。',
    judgingTitle: '评审建议', judgingIntro: '拟定 100 分标准，评委独立评分，观众票单列；最终以现场规则为准。',
    judgingCriteria: [['30', '问题与产品完整度'], ['25', 'Jev 使用是否恰当'], ['25', '测试与回退'], ['20', '演示表达']],
    faq: '来之前，你可能想知道',
    faqs: [['需要会写代码吗？', '欢迎开发者、设计师、产品人和对 AI 好奇的朋友。可以先带着问题报名；活动当天设有自由组队与选题确认环节。'], ['要提前准备什么？', '一台电脑、一个想解决的小问题，并提前阅读官方 Quick start。比赛将提供模型使用额度，具体模型、领取和使用规则以主办方通知为准；个人 API Key 请自行保管。'], ['提交后就算报名成功吗？', '提交后会保存报名意向，并显示待确认状态。主办方确认活动安排后进行审核，结果可在本页查看；正式到场信息通过报名邮箱联系。'], ['这是 TypeSafe 官方活动吗？', '这是云谷404发起的社区黑客松。最新海报列出活动伙伴，但没有宣称 TypeSafe 官方合作或赞助。']],
    registration: '下一位 Builder，', registrationAccent: '是你吗？', registrationBody: '无需完整方案。一句话讲清你想解决的问题，就可以开始。',
    login: '登录邮箱后申请', loginHint: '使用本站邮箱验证码登录，方便保存报名和查看结果。', loading: '正在读取报名状态…', retry: '重新加载',
    name: '如何称呼你', contact: '微信 / 其他联系方式（选填）', role: '你的角色', track: '感兴趣的方向', idea: '你想做什么？', ideaHint: '例如：把社区里的求助消息分给合适的人；不确定时先请人确认。至少 10 字。',
    roles: { developer: '开发者', designer: '设计师', product: '产品 / 创业者', curious: '好奇的探索者' },
    trackLabels: { router: '聪明的分流器', agent: 'Agent 的下一步', workflow: '会判断的工作流', explore: '还没想好，现场探索' },
    consent: '我同意主办方为本期报名审核与活动联络使用我提交的资料及账户邮箱。资料仅供本人和管理员查看，不公开展示。',
    submit: '提交报名意向', submitting: '正在提交…', received: '已收到你的报名意向', receipt: '报名编号', statuses: { pending: '待主办方确认', approved: '申请已通过', rejected: '本次未通过' },
    receiptHint: '可随时使用同一邮箱登录本页查看结果。具体到场安排以主办方通知为准。', feedback: '主办方反馈', email: '联络邮箱',
    errors: { unavailable: '暂时无法连接报名服务，请稍后重试。', network: '网络请求未完成，请重试；已保存的申请不会重复创建。', unauthorized: '登录已过期，请重新登录后提交。', forbidden: '无权执行此操作。', invalid_input: '请检查必填项、字数和资料使用同意选项。', already_reviewed: '该申请已被处理，请刷新列表。' },
    sources: '研究资料', checked: '依据官方资料与活动提案整理 · 2026.09.23', privacy: '需更正或删除报名资料，可联系活动主办方。',
  },
  en: {
    label: 'CLOUD VALLEY 404 · HACKATHON 002', badge: 'EXPRESSIONS OF INTEREST OPEN', title: ['Give AI', 'a next move.'],
    intro: 'Choose a real situation. Let Jev make a focused judgment, then let your code act. Bring a problem and build something that shows the full input → judgment → action path.', apply: 'Apply to join', learn: 'Meet Jev', poster: 'View latest poster', back: 'Back to events', date: 'Date', place: 'Location', capacity: 'Capacity / Fee', dateValue: 'Sep 27 · 10:00–20:00', placeValue: 'Yungu Center · B2-3F event area', capacityValue: 'Free · limited to 30 people',
    pendingInfo: 'The event is set for September 27, 10:00–20:00, at Yungu Center B2-3F. Registration is free and limited to 30 people. Model usage credits will be provided; the organizer will share access and usage rules. Applying does not reserve a seat.',
    about: 'A little judgment for your software.', aboutBody: 'Jev is TypeSafe AI’s System One model. Give it context and focused questions, receive structured answers, then let your code choose the next step.',
    primitives: [['Choice', 'Pick a path', 'Choose from defined options; receive probabilities and confidence.'], ['Score', 'Measure a dimension', 'Evaluate against an ordered rubric; receive a score, probabilities and confidence.'], ['Noul', 'Test a statement', 'Return a probability from 0 to 1 that a statement is true, without a separate confidence field.']],
    limit: 'Jev suits focused classification, scoring and judgments. Confidence is not accuracy; test thresholds against the risks in your use case and plan human review or another fallback for uncertainty.',
    lab: 'One judgment. Three paths.', labHint: 'Switch tickets to see how a decision connects to a product.', demo: 'Illustration · preset data, no live Jev call', input: 'INPUT', question: 'Where should this go?', output: 'APPLICATION ACTION',
    examples: [
      { name: 'Billing', text: 'I was charged twice for this order. Can you check?', choice: 'billing', confidence: '0.94', action: 'Route to billing support', values: [94, 4, 2] },
      { name: 'Bug report', text: 'The page crashes every time I click export.', choice: 'technical', confidence: '0.92', action: 'Route to technical support', values: [3, 92, 5] },
      { name: 'Unclear', text: 'Something seems wrong with my account…', choice: 'other', confidence: '0.18', action: 'Uncertain → human review', values: [29, 30, 41] },
    ],
    tracksTitle: 'Start with a small problem.', tracksIntro: 'Pick a starting point or bring a question of your own.',
    tracks: [['router', '01', 'A smarter router', 'Send messages, tickets or tasks to the right person or model.', 'Choice → route'], ['agent', '02', 'An agent’s next move', 'Decide whether to continue, ask for context or involve a human.', 'Noul → gate'], ['workflow', '03', 'A workflow with judgment', 'Filter content, organize feedback and prioritize work.', 'Score → rank']],
    plan: 'One day to build.', planIntro: 'September 27 · 10:00–20:00 · Event schedule',
    steps: [['10:00–10:30', 'Check-in and opening: Jev capabilities overview and development resources'], ['10:30–11:00', 'Open team formation and topic confirmation'], ['11:00–18:00', 'Focused development and on-site Q&A'], ['18:00–19:30', 'Project demos and judging'], ['19:30–20:00', 'Results, awards, and open conversation']],
    deliver: 'Show the full decision path.', deliverBody: 'Suggested deliverables: a working demo, at least one real Jev call, about 10 self-created test examples, and a fallback for uncertainty or failure. Existing projects and AI coding tools are welcome; explain what you built during the event.',
    judgingTitle: 'Proposed scoring', judgingIntro: 'A draft 100-point rubric with independent judging and a separate audience vote. Final rules will follow organizer updates.',
    judgingCriteria: [['30', 'Problem and product completeness'], ['25', 'Appropriate use of Jev'], ['25', 'Testing and fallback'], ['20', 'Demo and explanation']],
    faq: 'Before you join', faqs: [['Do I need to code?', 'Developers, designers, product people and curious builders are welcome. Apply with a problem in mind. The event includes open team formation and topic selection.'], ['What should I prepare?', 'Bring a laptop and a small problem. Read the official Quick start. The event will provide model usage credits; the organizer will share the model, access, and usage details. Keep personal API keys private.'], ['Does applying confirm my place?', 'Your interest is saved as pending. Organizers review applications once arrangements are confirmed. Check the result here; attendance details will be sent to your account email.'], ['Is this an official TypeSafe event?', 'This is a community hackathon by Cloud Valley 404. The latest poster lists event partners but does not claim official TypeSafe partnership or sponsorship.']],
    registration: 'The next builder.', registrationAccent: 'Could be you.', registrationBody: 'You do not need a complete plan. Start with the problem you want to solve.', login: 'Sign in with email to apply', loginHint: 'Use an email verification code to save your application and check its status.', loading: 'Loading your application…', retry: 'Reload',
    name: 'Your name', contact: 'WeChat / other contact (optional)', role: 'Your role', track: 'Your direction', idea: 'What would you like to build?', ideaHint: 'For example: route community requests to the right person, with human review when uncertain. At least 10 characters.',
    roles: { developer: 'Developer', designer: 'Designer', product: 'Product / Founder', curious: 'Curious explorer' }, trackLabels: { router: 'A smarter router', agent: 'An agent’s next move', workflow: 'A workflow with judgment', explore: 'Explore at the event' },
    consent: 'I agree that organizers may use my application and account email for this event’s review and communication. Only I and administrators can view these details.', submit: 'Submit my interest', submitting: 'Submitting…', received: 'We received your interest', receipt: 'APPLICATION ID', statuses: { pending: 'Awaiting organizer review', approved: 'Application approved', rejected: 'Not selected this time' }, receiptHint: 'Sign in with the same email to check your result. Attendance details are subject to the organizer’s notice.', feedback: 'Organizer feedback', email: 'Contact email',
    errors: { unavailable: 'Application service is unavailable. Please try again later.', network: 'Request did not complete. Retry safely; saved applications will not be duplicated.', unauthorized: 'Your session expired. Sign in again to submit.', forbidden: 'You do not have access to this action.', invalid_input: 'Check the required fields, lengths and consent.', already_reviewed: 'This application was already reviewed. Refresh the list.' }, sources: 'RESEARCH & RESOURCES', checked: 'Based on official sources and the event proposal · 2026.09.23', privacy: 'Contact the organizers to correct or delete your application.',
  },
};
