export const managementCopy = {
  zh: {
    workQueue: '审核工作台', waiting: n => `${n} 条申请等待处理`, queueClear: '待办已清空', queueClearHint: '新申请到来后会显示在这里。', oldestPending: '最早待审提交于', overdue: '等待超过 48 小时', blockedPending: n => `${n} 条申请所属账户已停用`, processQueue: '从最早申请开始',
    trend: '近 7 天动态', utcDays: '按 UTC 自然日统计，含今天', utcDates: '日期范围按 UTC 计算', trend_users: '新注册', trend_applications: '新申请', trend_reviews: '已审核', trendData: '查看每日明细', date: '日期', updatedAt: '更新于',
    userDetails: '用户详情', close: '关闭详情', recentRequests: '最近 5 条申请', recentActivity: '最近 5 条操作', viewAll: '查看全部', auditSearch: '搜索操作人、用户邮箱、用户 ID、原因或申请编号', actionType: '操作类型', allActions: '全部操作', fromDate: '开始日期', toDate: '结束日期',
    filterStatus: '状态', sortOrder: '排序', oldestFirst: '最早提交优先', newestFirst: '最新提交优先', filteredUser: '当前用户', removeFilter: '移除用户筛选', disabledReviewHint: '该用户已停用，恢复账户后才能审批。',
    accountTitle: '个人中心', accountIntro: '管理你的资料、申请和登录会话。', login: '登录账户', loginHint: '登录后查看你的账户与项目进度。',
    profile: '账户资料', save: '保存资料', saved: '已保存。', verified: '邮箱已验证', member: '社区成员', administrator: '管理员',
    overview: '数据概览', audit: '操作记录', applications: '累计申请', pending: '待审核申请', granted: '累计发放 Token', votes: '已发布模型投票',
    users: '注册用户', active: '正常账户', disabled: '停用账户', newUsers: '近 7 天新用户', online: '有有效会话的用户', approved: '已通过申请', rejected: '未通过申请',
    sessions: '有效登录会话', security: '登录与安全', sessionHint: '会话代表一次有效登录，不等同于设备数量。有效期结束后需要重新登录。',
    sessionStarted: '登录时间', current: '当前会话', other: '其他会话', expires: '到期时间', revokeOthers: '退出其他会话', revokeHint: '其他登录会话将立即失效，保留当前登录。', logout: '退出当前登录', confirmLogout: '确定退出当前登录？',
    quickLinks: '常用入口', tokens: '申请 / 领取 Token', tokensHint: '查看审核进度、领取 API Key 与使用说明', tier: '我的锐评', tierHint: '查看已发布投票，继续制作本机白板', guide: '创作指南', guideHint: '了解活动规则与作品提交方式',
    actions: '操作', enable: '启用账户', disable: '停用账户', revoke_sessions: '强制下线', protected: '管理员保护', reason: '操作原因', reasonHint: '请填写原因，便于后续追溯（最多 300 字）', cancel: '取消', confirm: '确认操作',
    disableHint: '停用后无法登录或领取密钥，现有会话也会失效。启用后可重新登录。此操作不会撤销供应商侧 API Key。', enableHint: '恢复此账户的登录权限，原有会话不会恢复。', revoke_sessionsHint: '使该用户的全部现有会话失效；用户仍可以重新登录。',
    actionSaved: '操作已完成。', requestSearch: '搜索项目、邮箱、昵称或用户 ID', clear: '重置筛选', actor: '操作人', target: '目标用户', detail: '原因 / 申请编号', time: '操作时间', noAudit: '暂无操作记录。', token_approved: '通过 Token 申请', token_rejected: '拒绝 Token 申请',
    statsHint: '额度为累计发放记录，不代表 API 实时余额或消耗。', accountLink: '个人中心', errors: { protected_account: '无法修改自己或配置中的管理员账户。', invalid_nickname: '昵称最多 32 字，不能包含控制字符。', not_found: '目标记录不存在，请刷新重试。' },
  },
  en: {
    workQueue: 'REVIEW DESK', waiting: n => `${n} applications awaiting review`, queueClear: 'All caught up', queueClearHint: 'New applications will appear here.', oldestPending: 'Oldest submitted', overdue: 'Waiting over 48 hours', blockedPending: n => `${n} applications from disabled accounts`, processQueue: 'Review oldest first',
    trend: 'Last 7 days', utcDays: 'UTC calendar days, including today', utcDates: 'Date range uses UTC', trend_users: 'New users', trend_applications: 'Applications', trend_reviews: 'Reviews', trendData: 'View daily counts', date: 'Date', updatedAt: 'Updated',
    userDetails: 'User details', close: 'Close details', recentRequests: 'Latest 5 applications', recentActivity: 'Latest 5 actions', viewAll: 'View all', auditSearch: 'Search actor, user email, user ID, reason, or application ID', actionType: 'Action type', allActions: 'All actions', fromDate: 'From date', toDate: 'To date',
    filterStatus: 'Status', sortOrder: 'Sort', oldestFirst: 'Oldest first', newestFirst: 'Newest first', filteredUser: 'Selected user', removeFilter: 'Remove user filter', disabledReviewHint: 'This account is disabled. Restore access before reviewing.',
    accountTitle: 'Your account', accountIntro: 'Manage your profile, applications, and sign-in sessions.', login: 'Sign in', loginHint: 'Sign in to view your account and project progress.',
    profile: 'Profile', save: 'Save profile', saved: 'Saved.', verified: 'Email verified', member: 'Community member', administrator: 'Administrator',
    overview: 'Overview', audit: 'Activity log', applications: 'Applications', pending: 'Pending applications', granted: 'Tokens issued', votes: 'Published model votes',
    users: 'Registered users', active: 'Active accounts', disabled: 'Disabled accounts', newUsers: 'Joined in 7 days', online: 'Users with valid sessions', approved: 'Approved applications', rejected: 'Declined applications',
    sessions: 'Valid sign-in sessions', security: 'Sign-in & security', sessionHint: 'Each session represents a sign-in, not a unique device. Sign in again after it expires.',
    sessionStarted: 'Signed in', current: 'Current session', other: 'Other session', expires: 'Expires', revokeOthers: 'Sign out other sessions', revokeHint: 'All other sessions will end. This session stays signed in.', logout: 'Sign out', confirmLogout: 'Sign out of this session?',
    quickLinks: 'Quick links', tokens: 'Apply / collect tokens', tokensHint: 'Track reviews and collect your API key and instructions', tier: 'My rankings', tierHint: 'View published votes and continue your local board', guide: 'Creator guide', guideHint: 'Activity rules and how to submit your work',
    actions: 'Actions', enable: 'Enable account', disable: 'Disable account', revoke_sessions: 'End all sessions', protected: 'Protected admin', reason: 'Reason', reasonHint: 'Explain the action for the activity log (up to 300 characters)', cancel: 'Cancel', confirm: 'Confirm action',
    disableHint: 'Blocks sign-in and key collection, and ends existing sessions. Access can be restored. Provider API keys are not revoked.', enableHint: 'Restore sign-in access. Previous sessions are not restored.', revoke_sessionsHint: 'End all existing sessions. The user can still sign in again.',
    actionSaved: 'Action completed.', requestSearch: 'Search project, email, nickname, or user ID', clear: 'Reset filters', actor: 'Actor', target: 'Target user', detail: 'Reason / application ID', time: 'Time', noAudit: 'No activity yet.', token_approved: 'Approved token application', token_rejected: 'Declined token application',
    statsHint: 'Tokens issued is a historical total, not a live API balance or usage measurement.', accountLink: 'Your account', errors: { protected_account: 'You cannot modify yourself or a configured administrator.', invalid_nickname: 'Use up to 32 characters without control characters.', not_found: 'Record not found. Please refresh.' },
  },
};
