// Shared by local-only apps that explicitly link to this policy.
// Revisit the policy before adding accounts, uploads, analytics, ads or purchases.
export const privacyPolicy = {
  confirmed: true,
  email: "kinggreenhall@gmail.com",
  updated: "2026-09-22",
};

export const privacySections = [
  {
    id: "scope", zh: "适用范围", en: "Scope",
    chinese: [
      "本政策适用于由相应 App Store 产品页所列开发者提供、并在应用内或产品页明确链接本政策的软件（下称“应用”）。本政策中的“我们”指该应用的开发者。",
      "这些应用仅在您的设备上处理数据，不提供账户登录、数据上传、使用行为统计或应用内购买功能。本政策不适用于承载本网页的网站及其账户、活动或其他在线服务。",
    ],
    english: [
      "This policy applies to software provided by the developer identified on the relevant App Store product page that expressly links to this policy in the app or its listing (the “App”). “We” refers to that App’s developer.",
      "These apps process data only on your device. They do not offer account sign-in, data uploads, usage analytics or in-app purchases. This policy does not cover the website hosting this page or its accounts, events or other online services.",
    ],
  },
  {
    id: "information", zh: "本机处理的信息", en: "Information processed on your device",
    chinese: [
      "应用根据您使用的功能，在设备上处理您主动输入、选择或授权访问的内容，例如文字、照片、视频、音频或文件，以及提供功能所需的相关信息。仅当相应应用提供相关功能时，才会访问对应内容。",
      "这些内容及应用产生的设置、工作记录和处理结果保存在本机，不会由应用上传至开发者或第三方服务器。我们不会通过应用收集您的账户信息、使用行为、设备标识符或位置轨迹，也无法远程查看您在应用中处理的内容。",
      "应用不集成用于使用行为统计或广告追踪的第三方 SDK，不出售或出租您的个人信息，也不进行跨应用、跨网站广告追踪。",
    ],
    english: [
      "Depending on the features you use, the App processes content you enter, select or permit it to access on your device, such as text, photos, videos, audio or files, together with information needed to provide the feature. A category of content is accessed only if the particular App offers a corresponding feature.",
      "This content, together with settings, work records and results generated by the App, remains on your device and is not uploaded by the App to developer or third-party servers. We do not collect account information, usage activity, device identifiers or location history through the App and cannot remotely view the content you process in it.",
      "The App does not integrate third-party SDKs for usage analytics or advertising tracking. We do not sell or rent your personal information or track you across apps or websites for advertising.",
    ],
  },
  {
    id: "permissions", zh: "设备权限与您的选择", en: "Permissions and your choices",
    chinese: [
      "应用仅在您使用相应功能时请求必要的系统权限，并通过权限提示说明用途。例如，照片权限用于处理您授权的照片或视频；相机或麦克风权限仅用于您主动发起的拍摄或录音功能。未提供相应功能的应用不会因此请求这些权限。获得权限不代表内容会离开您的设备。",
      "您可以拒绝授权，或在 iOS“设置”中随时调整。拒绝后，依赖该权限的功能可能无法使用，其他不依赖该权限的功能仍可使用。如系统提供有限照片访问或单独文件选择，您可以只授权所需内容。",
      "撤回权限会停止后续基于该权限的访问，但不会自动删除已经保存在应用中的数据或您主动导出的副本；删除方式见下文。",
    ],
    english: [
      "The App requests necessary system permissions only when you use a related feature and explains their purpose in the permission prompt. For example, photo access is used to process authorized photos or videos; camera or microphone access is used only for capture or recording you initiate. Apps without those features do not request those permissions on that basis. Granting permission does not mean content leaves your device.",
      "You can decline or change permissions in iOS Settings at any time. Features dependent on that permission may be unavailable, while independent features remain usable. Where limited photo access or individual file selection is available, you can select only the content needed.",
      "Revoking permission stops future access based on that permission but does not automatically delete data already saved in the App or copies you deliberately exported. Deletion options are described below.",
    ],
  },
  {
    id: "sharing", zh: "系统服务与主动分享", en: "System services and sharing",
    chinese: [
      "应用不会自动向第三方传输您的内容。如您主动使用系统分享、导出或“存储到文件”等功能，所选内容将交由您指定的应用或位置处理，后续处理适用相应接收方的隐私政策。请在分享前确认接收对象。",
      "应用本身不提供云端上传或同步服务。iOS、iCloud 或您选择的存储服务可能依据您的系统设置备份或同步设备数据，这属于相关系统或服务的行为。您可以在相应设置中管理备份、同步和副本。Apple 的系统诊断共享由您的系统设置及 Apple 的隐私政策管理。",
    ],
    english: [
      "The App does not automatically transmit your content to third parties. If you choose system sharing, export or Save to Files, selected content is handled by the app or destination you choose, whose subsequent processing is governed by its own privacy policy. Check the recipient before sharing.",
      "The App itself does not provide cloud uploads or synchronization. iOS, iCloud or storage services you choose may back up or synchronize device data according to your system settings. These are actions of the relevant system or service. Manage backups, synchronization and copies in the corresponding settings. Apple’s system diagnostic sharing is governed by your system settings and Apple’s privacy policy.",
    ],
  },
  {
    id: "retention", zh: "保存、安全与删除", en: "Retention, security and deletion",
    chinese: [
      "应用数据保存在您的设备中，保留至您通过应用提供的删除功能、系统存储管理或删除应用等方式将其移除。仅“卸载 App”以保留文稿和数据，与“删除 App”不同，可能仍会保留应用数据。",
      "删除应用不会自动删除照片图库中的原始内容、您导出的文件、系统备份或云端副本。这些内容需要在照片、文件、备份或相应存储服务中单独管理。",
      "您可以通过应用或系统提供的功能访问、修改、导出（如提供）和删除本机内容，并随时撤回设备权限。由于我们不持有应用内的本机数据，无法代您远程访问、恢复或删除这些内容。应用不设账户，因此无需办理账户注销。",
      "应用依赖系统沙盒和设备提供的安全机制保护本地数据。请妥善保管设备、设置设备密码，并谨慎管理共享与备份。",
    ],
    english: [
      "App data is stored on your device until you remove it using available in-app deletion tools, system storage controls or by deleting the App. Offloading an app while keeping its documents and data is different from deleting it and may retain its data.",
      "Deleting the App does not automatically delete original items in your photo library, exported files, system backups or cloud copies. Manage those separately in Photos, Files, backups or the relevant storage service.",
      "Use available App or system features to access, modify, export (where supported) and delete local content, and revoke device permissions at any time. Because we do not hold your local App data, we cannot remotely access, restore or delete it for you. There is no App account to delete.",
      "The App relies on the system sandbox and device security mechanisms to protect local data. Keep your device secure, set a device passcode and manage sharing and backups carefully.",
    ],
  },
  {
    id: "support", zh: "联系支持时的信息", en: "Information when contacting support",
    chinese: [
      "如果您主动通过电子邮件联系我们，我们会收到您的邮箱地址、邮件正文和您附带的附件。这些信息由您主动提供，用于答复咨询、排查问题或处理隐私请求，不属于应用自动收集的数据。请勿发送与问题无关的敏感内容。",
      "支持邮件通过邮箱服务提供方处理。我们仅在处理请求、必要的后续沟通或履行适用法律义务所需期间内保留相关信息；不再需要时删除。您可以通过下方邮箱请求访问、更正或删除您提供的信息。必要时我们会核实您的身份；如法律要求保留部分信息，会向您说明原因。",
    ],
    english: [
      "If you choose to email us, we receive your email address, message and any attachments you include. You provide this information voluntarily so we can answer questions, troubleshoot issues or handle privacy requests. It is not automatically collected by the App. Please avoid sending sensitive content unrelated to your request.",
      "Support emails are processed through the email service provider. We retain this information only as long as needed to handle the request, necessary follow-up or applicable legal obligations, and delete it when no longer needed. You may use the email below to request access, correction or deletion of information you provided. We may verify your identity and will explain if any information must be retained by law.",
    ],
  },
  {
    id: "children", zh: "未成年人保护", en: "Children’s privacy",
    chinese: [
      "应用对未成年人的数据采取相同的本机处理方式，不会通过应用收集其个人信息。未成年人应在适用法律要求时取得监护人同意后使用应用。监护人如认为孩子通过支持邮件等方式向我们提供了需要删除的个人信息，可以联系我们处理。",
    ],
    english: [
      "The same on-device processing applies to minors, and the App does not collect their personal information. Minors should obtain a parent’s or guardian’s consent where required by applicable law. Guardians who believe a child has provided personal information through support emails or similar contact and wish it deleted may contact us.",
    ],
  },
  {
    id: "updates", zh: "政策更新", en: "Policy updates",
    chinese: [
      "应用功能或数据处理方式发生变化时，我们会更新本政策及页面日期。涉及个人信息处理的重大变化会通过应用内提示或其他合适方式告知；需要取得同意时，会在相关处理开始前征求同意。",
    ],
    english: [
      "When features or data practices change, we will update this policy and its date. Material changes to personal information processing will be communicated in the App or through another appropriate channel. Where consent is required, it will be requested before the relevant processing begins.",
    ],
  },
];
