export const tierCopy = {
  zh: {
    title: "从夯到拉", eyebrow: "锐评小工具 / 001", tagline: "你的标准，你来排。",
    intro: "把万物做成贴纸，给它们找个位置。", sharedIntro: "这就是我的排名。你怎么排？",
    tiers: ["夯", "顶级", "人上人", "NPC", "拉完了"], tierNotes: ["无可替代", "真的很强", "有点东西", "平平无奇", "一言难尽"],
    titleLabel: "白板标题", titlePlaceholder: "给这份排名起个名…", defaultTitle: "万物皆可从夯到拉",
    share: "分享白板 ↗", sharing: "正在生成链接…", shareNote: "免登录 · 只读分享 · 只分享已上榜贴纸",
    shareHelp: "获得链接的人都能查看。分享后继续编辑，不会改变这个版本。",
    shared: "分享版 · 只读", create: "我也排一个 ↗", copy: "复制链接", copied: "链接已复制", copyManual: "请选中链接手动复制。",
    linkReady: "专属链接已生成", linkLabel: "分享链接", openShare: "打开分享页 ↗", close: "收起",
    updated: "白板已有新改动，再次分享可生成新版本。", loading: "正在打开白板…", loadError: "暂时打不开这块白板，请重试。", missing: "这块白板不存在，请检查分享链接。", retry: "重新加载",
    studio: "贴纸工作台", studioNote: "选个 Logo，或者做张文字贴纸。", textTab: "文字贴纸", imageTab: "Logo 贴纸",
    logoLibrary: "官方 Logo", logoNote: "拖到白板 · 或选中后点击档位", logoSelect: "选择 Logo 贴纸", chooseTier: "已选中贴纸，点击档位上榜。", allRanked: "官方 Logo 都已上榜，放回后会重新出现在这里。",
    stickerText: "贴纸文字", textPlaceholder: "比如：凌晨两点的灵感", colorLabel: "贴纸颜色",
    colors: ["奶白", "珊瑚红", "奶油黄", "薄荷绿", "晴空蓝", "樱花粉"], add: "＋ 生成贴纸", preview: "贴纸预览", previewText: "灵感万岁",
    customLogo: "自定义 Logo", customLogoNote: "上传自己的图片", customLogoHelp: "选一张图片，制作成你的 Logo 贴纸。", optional: "（选填）", closeDialog: "关闭弹框",
    upload: "选择图片并生成贴纸", uploadNote: "PNG / JPG / WebP · 最大 500 KB · 最多 6 个", imageLabel: "Logo 名称", imagePlaceholder: "不填则使用文件名", processing: "正在制作贴纸…",
    tray: "自定义贴纸", trayNote: "拖到白板，或者选中后点档位。", trayEmpty: "上传的 Logo 和制作的文字贴纸会放在这里。", try: "没灵感？试试这些", presets: ["☕ 咖啡", "💡 灵感", "写代码", "周一", "准时下班", "临时需求"],
    empty: "把贴纸放这里", place: "放入", selected: "已选中", move: "移动到", remove: "删除贴纸", deselect: "取消选择", earlier: "向前移", later: "向后移",
    undo: "撤销", clear: "清空", clearConfirm: "清空当前草稿？已分享的白板仍会保留。", yesClear: "确认清空", cancel: "取消",
    dragReturn: "放回", releaseReturn: "松手放回", returnLogoHint: "回到官方 Logo", returnCustomHint: "回到自定义贴纸", returnToTray: "放回", returnedLogo: "已放回官方 Logo 区。", returnedCustom: "已放回自定义贴纸区。", undoReturn: "撤销放回", undoDelete: "撤销删除",
    saved: "草稿已保存在本机", saving: "正在保存草稿…", storageError: "本机存储不可用，请及时分享保存。", restoredError: "旧草稿无法读取，已打开空白板。",
    limit: "最多放 40 张贴纸，请先删除几张。", customLogoLimit: "最多上传 6 个自定义 Logo，请先删除一个再上传。", imageError: "图片无法读取，请换一张 PNG、JPG 或 WebP。", imageSize: "图片不能超过 500 KB。", tooLarge: "贴纸图片总量过大，请减少几张 Logo 后重试。",
    shareError: "分享暂时失败，草稿还在，请稍后重试。", rateLimited: "分享太频繁，请一分钟后再试。", emptyShare: "先把至少一张贴纸放到白板上。",
    made: "贴纸已生成，选一个档位吧。", moved: "贴纸已移动到", deleted: "贴纸已删除。", credit: "排名没有标准答案，快乐有。", count: "张贴纸", boardLabel: "从夯到拉排名白板", ready: "准备就绪",
  },
  en: {
    title: "GOAT to Nope", eyebrow: "HOT TAKE TOOL / 001", tagline: "Your taste. Your tiers.",
    intro: "Turn anything into a sticker. Give it a place.", sharedIntro: "Here's my ranking. What's yours?",
    tiers: ["GOAT", "Elite", "Solid", "NPC", "Nope"], tierNotes: ["Irreplaceable", "Really good", "Has potential", "Just average", "No words"],
    titleLabel: "Board title", titlePlaceholder: "Give your ranking a name…", defaultTitle: "Everything deserves a tier",
    share: "Share board ↗", sharing: "Creating link…", shareNote: "No account · Read-only links · Ranked stickers only",
    shareHelp: "Anyone with the link can view this version. Further edits won't change it.",
    shared: "Shared version · Read only", create: "Make my own ↗", copy: "Copy link", copied: "Link copied", copyManual: "Select the link and copy it manually.",
    linkReady: "Your unique link is ready", linkLabel: "Share link", openShare: "Open shared board ↗", close: "Close",
    updated: "You have new edits. Share again to create another version.", loading: "Opening board…", loadError: "Couldn't load this board. Please try again.", missing: "Board not found. Please check the link.", retry: "Retry",
    studio: "Sticker studio", studioNote: "Pick a logo, or make a text sticker.", textTab: "Text sticker", imageTab: "Logo sticker",
    logoLibrary: "Official logos", logoNote: "Drag to a tier · Or select, then pick a tier", logoSelect: "Select logo sticker", chooseTier: "Sticker selected. Pick a tier.", allRanked: "All logos are ranked. Put one back to see it here again.",
    stickerText: "Sticker text", textPlaceholder: "e.g. That 2 AM idea", colorLabel: "Sticker color",
    colors: ["Paper", "Coral", "Butter", "Mint", "Sky", "Pink"], add: "＋ Make sticker", preview: "Sticker preview", previewText: "Stay curious",
    customLogo: "Custom logo", customLogoNote: "Upload your own image", customLogoHelp: "Choose an image to make your own logo sticker.", optional: "(optional)", closeDialog: "Close dialog",
    upload: "Choose image & make sticker", uploadNote: "PNG / JPG / WebP · Up to 500 KB · 6 logos max", imageLabel: "Logo name", imagePlaceholder: "Leave blank to use the filename", processing: "Making sticker…",
    tray: "Custom stickers", trayNote: "Drag onto the board, or select then tap a tier.", trayEmpty: "Your uploaded logos and text stickers appear here.", try: "Need a starting point?", presets: ["☕ Coffee", "💡 Ideas", "Coding", "Mondays", "Clocking out", "Last-minute asks"],
    empty: "Drop a sticker here", place: "Place in", selected: "Selected", move: "Move to", remove: "Delete sticker", deselect: "Deselect", earlier: "Move earlier", later: "Move later",
    undo: "Undo", clear: "Clear", clearConfirm: "Clear this draft? Shared boards will still be available.", yesClear: "Clear draft", cancel: "Cancel",
    dragReturn: "Put back", releaseReturn: "Release to return", returnLogoHint: "To official logos", returnCustomHint: "To custom stickers", returnToTray: "Put back", returnedLogo: "Returned to official logos.", returnedCustom: "Returned to custom stickers.", undoReturn: "Undo return", undoDelete: "Undo deletion",
    saved: "Draft saved on this device", saving: "Saving draft…", storageError: "Device storage unavailable. Share to save your board.", restoredError: "Couldn't read the old draft. Starting with a blank board.",
    limit: "Up to 40 stickers. Remove a few to add more.", customLogoLimit: "You can upload up to 6 custom logos. Delete one before adding another.", imageError: "Couldn't read that image. Try a PNG, JPG or WebP.", imageSize: "Images must be 500 KB or smaller.", tooLarge: "Too much image data. Remove a few logos and try again.",
    shareError: "Sharing failed. Your draft is safe here. Please try again.", rateLimited: "Too many shares. Please wait one minute.", emptyShare: "Place at least one sticker on the board first.",
    made: "Sticker ready. Pick a tier.", moved: "Sticker moved to", deleted: "Sticker deleted.", credit: "No right answers. Just good fun.", count: "stickers", boardLabel: "Tier ranking board", ready: "Ready",
  },
};
