export const tokenCopy = {
  zh: {
    title: '让好想法，开始运行。', eyebrow: '免费 TOKEN 计划', intro: '这是面向项目的独立支持计划。告诉我们你正在做什么；审核通过后，在这里领取 API Key 和使用说明。单场活动的模型额度以活动说明为准。',
    apply: '提交申请', projectName: '项目名称', projectPlaceholder: '你想做出的那个作品', purpose: '项目介绍与 Token 用途', purposePlaceholder: '介绍你的想法、计划使用的模型，以及 Token 会用在哪些功能上（至少 10 字）。',
    requestedTokens: '期望 Token 数量', amountHint: '请填写 1 至 1,000,000,000 之间的整数，实际额度以审批结果为准。',
    signIn: '登录后申请', signInHint: '使用邮箱登录，保存申请并随时查看审核进度。', loading: '正在加载…', working: '正在处理…', history: '我的申请', empty: '还没有申请，从你的第一个想法开始。',
    pending: '待审核', approved: '已通过', rejected: '未通过', refresh: '刷新', requested: '申请额度', granted: '获批额度', submitted: '提交时间', reviewed: '审核时间', note: '审核反馈 / 使用说明',
    queued: '申请已提交，可在下方查看审核进度。', cannotApply: '每个账户可领取一次免费额度。待审核时无需重复申请；未通过后可以完善内容重新提交。',
    yourKey: '你的 API Key', reveal: '查看 API Key', hide: '隐藏 API Key', copy: '复制 API Key', copied: '已复制', copyFailed: '复制失败，请手动选择密钥复制。', keyHint: '请妥善保存 API Key，不要公开或提交到代码仓库。',
    adminTitle: '管理后台', adminIntro: '查看社区用户，为正在起步的作品提供支持。', users: '全部用户', requests: '申请审批', all: '全部状态', search: '搜索邮箱、昵称或用户 ID', searchButton: '搜索',
    user: '用户', email: '邮箱', userId: '用户 ID', nickname: '昵称', registered: '注册时间', accountStatus: '账户状态', active: '正常', disabled: '已停用', requestCount: '申请次数',
    noUsers: '没有匹配的用户。', noRequests: '没有符合条件的申请。', forbidden: '此账户没有管理权限。请使用已配置的管理员邮箱登录。', adminSignIn: '请先登录管理员账户。',
    approve: '通过并发放', reject: '拒绝申请', apiKey: '发放的 API Key', keyPlaceholder: '填写已创建、可用的项目专属 API Key', reviewNote: '使用说明或拒绝原因', notePlaceholder: '通过时填写服务地址、支持模型、额度及有效期；拒绝时说明原因。申请人可见。',
    reviewSaved: '审批已保存。', reviewer: '审核人', total: n => `共 ${n} 条`, page: (p, n) => `第 ${p} / ${n} 页`, previous: '上一页', next: '下一页',
    errors: { unavailable: '服务暂不可用，请稍后重试。', network: '网络连接失败，请重试。', unauthorized: '登录已失效，请重新登录。', forbidden: '没有权限执行此操作。', invalid_input: '请检查填写内容、长度和 Token 数量。', too_large: '填写内容过长，请缩短后重试。', already_applied: '已有待审核或已通过的申请，请刷新查看。', review_conflict: '此申请已被处理或账户已停用，请刷新查看。', rate_limited: '操作过于频繁，请一分钟后重试。', delivery_unavailable: '密钥发放尚未配置，请管理员设置加密密钥后重试。', not_found: '未找到可领取的 API Key。' },
  },
  en: {
    title: 'Give your idea a head start.', eyebrow: 'FREE TOKEN PROGRAM', intro: 'This is a separate program for projects. Tell us what you are building; once approved, return here for your API key and setup instructions. Event model credits follow each event\'s own terms.',
    apply: 'Submit application', projectName: 'Project name', projectPlaceholder: 'What will you build?', purpose: 'Project and token usage', purposePlaceholder: 'Describe your idea, intended models, and how you will use the tokens (at least 10 characters).',
    requestedTokens: 'Requested tokens', amountHint: 'Enter a whole number from 1 to 1,000,000,000. Final allocation is decided during review.', signIn: 'Sign in to apply', signInHint: 'Sign in with your email to save an application and track its progress.', loading: 'Loading…', working: 'Working…', history: 'My applications', empty: 'No applications yet. Start with your first idea.',
    pending: 'Pending', approved: 'Approved', rejected: 'Declined', refresh: 'Refresh', requested: 'Requested tokens', granted: 'Granted tokens', submitted: 'Submitted', reviewed: 'Reviewed', note: 'Feedback / setup instructions',
    queued: 'Application submitted. Track its progress below.', cannotApply: 'One free allocation per account. Please wait while your application is pending. You may reapply after a decline.',
    yourKey: 'Your API key', reveal: 'Show API key', hide: 'Hide API key', copy: 'Copy API key', copied: 'Copied', copyFailed: 'Copy failed. Please select and copy the key manually.', keyHint: 'Keep your API key private. Do not publish it or commit it to a repository.',
    adminTitle: 'Admin', adminIntro: 'Meet the community and support their next project.', users: 'All users', requests: 'Applications', all: 'All statuses', search: 'Search email, nickname, or user ID', searchButton: 'Search',
    user: 'User', email: 'Email', userId: 'User ID', nickname: 'Nickname', registered: 'Joined', accountStatus: 'Account status', active: 'Active', disabled: 'Disabled', requestCount: 'Applications',
    noUsers: 'No matching users.', noRequests: 'No matching applications.', forbidden: 'This account does not have admin access. Sign in with a configured admin email.', adminSignIn: 'Sign in with your admin account to continue.',
    approve: 'Approve and issue', reject: 'Decline application', apiKey: 'API key to issue', keyPlaceholder: 'An existing, working API key dedicated to this project', reviewNote: 'Setup instructions or reason for declining', notePlaceholder: 'For approval, include endpoint, supported models, allocation, and expiry. For a decline, explain why. Visible to the applicant.',
    reviewSaved: 'Review saved.', reviewer: 'Reviewed by', total: n => `${n} total`, page: (p, n) => `Page ${p} of ${n}`, previous: 'Previous', next: 'Next',
    errors: { unavailable: 'Service unavailable. Please try again.', network: 'Connection failed. Please try again.', unauthorized: 'Your session expired. Please sign in again.', forbidden: 'You do not have permission.', invalid_input: 'Check the fields, text lengths, and token amount.', too_large: 'Please shorten the submitted text.', already_applied: 'An application is already pending or approved. Refresh to view it.', review_conflict: 'This application was already reviewed or the account is disabled. Please refresh.', rate_limited: 'Too many requests. Try again in one minute.', delivery_unavailable: 'Key delivery is not configured. An administrator must set the encryption key.', not_found: 'No API key is available for this application.' },
  },
};
